### ISSUE TITLE
Provide ability to edit the registrant inline with registration

### ISSUE THREAD

**Issue by dpi** [dpi/rng#102]
Part of #99 

Add new configuration for event types:

``` yml
per_event_type:
    per_identity entity_type_bundle:
         registrant_entity_bundle:
           type: string
         mirror_operation_from_registration:
           type: boolean
           descripton: 'grant permission to access registrant metadata if the user has the same access rights to the parent registration.'
```
